# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('interduce', models.CharField(max_length=100, null=True)),
                ('sex', models.NullBooleanField()),
                ('address', models.CharField(max_length=30, null=True)),
                ('avatar', models.CharField(max_length=100, null=True, verbose_name='头像')),
            ],
        ),
    ]
