# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
