# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botitle', models.CharField(max_length=50)),
                ('bocontent', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('view_count', models.BigIntegerField(db_index=True, default=0)),
                ('up_count', models.BigIntegerField(default=0)),
                ('down_count', models.BigIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qttitle', models.CharField(max_length=50)),
                ('qtdetail', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Up_Down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_up', models.BooleanField(verbose_name='是否为赞')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog', verbose_name='文章')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('join_time', models.DateTimeField(auto_now=True)),
                ('signature', models.CharField(max_length=100, null=True)),
                ('sex', models.NullBooleanField()),
                ('address', models.CharField(max_length=30, null=True)),
                ('follow_count', models.BigIntegerField(default=0)),
                ('fans_count', models.BigIntegerField(default=0)),
                ('avatar', models.URLField(default='/static/img/white.png', verbose_name='头像')),
                ('fan', models.ManyToManyField(related_name='follow', to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='up_down',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='赞或踩的用户'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='q_tag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='b_tag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog'),
        ),
    ]
