# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170730_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='/static/img/white.png', verbose_name='头像'),
        ),
    ]
