# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170805_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
