# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up_Down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_up', models.BooleanField(verbose_name='是否为赞')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='赞或踩的用户')),
            ],
        ),
    ]
