# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_up_down'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Q_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
