# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170811_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fans_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
