# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170812_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='to_user',
        ),
        migrations.AddField(
            model_name='user',
            name='fan',
            field=models.ManyToManyField(related_name='follow', to='app.User'),
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
    ]
